//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "t_space_article")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32, // 文章id
    pub title: String, // 文章标题
    #[sea_orm(column_type = "Text")]
    pub description: String, // 文章描述
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")")]
    pub content: String, // 文章内容
    pub is_top: bool,  // 是否置顶
    pub status_type: i32, // 文章状态，0.草稿、1.已发布、2.隐藏、3.删除
    pub create_time: DateTime, // 创建时间
    pub update_time: DateTime, // 更新时间
    pub create_user_id: i32, // 创建用户id
    pub update_user_id: i32, // 更新用户id
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreateUserId",
        to = "super::user::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    CreateUser,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UpdateUserId",
        to = "super::user::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    UpdateUser,
}

impl ActiveModelBehavior for ActiveModel {}
