//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "t_space_tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32, // 标签id
    pub name: String,                  // 标签名称
    pub parent_tag_id: Option<i32>,    // 父标签id
    pub thumbnail_url: Option<String>, // 缩略图url
    pub status_type: i32,              // 标签状态，0.正常、1.隐藏、2.删除
    pub create_time: DateTime,         // 创建时间
    pub update_time: DateTime,         // 更新时间
    pub create_user_id: i32,           // 创建用户id
    pub update_user_id: i32,           // 更新用户id
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentTagId",
        to = "Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    ParentTag,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreateUserId",
        to = "super::user::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    CreateUser,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UpdateUserId",
        to = "super::user::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    UpdateUser,
}

impl ActiveModelBehavior for ActiveModel {}
