//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "t_space_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32, // 用户id
    #[sea_orm(unique)]
    pub username: String, // 用户名
    pub nickname: String,           // 昵称
    pub password: String,           // 密码（加密）
    pub email: String,              // 邮箱
    pub avatar_url: Option<String>, // 头像url
    pub signature: String,          // 个性签名
    pub group_type: i32,            // 用户组类型 0.普通用户、1.管理员
    pub status_type: i32,           // 用户状态，0.等待、1.激活、2.禁用、3.删除
    pub create_time: DateTime,      // 创建时间
    pub update_time: DateTime,      // 更新时间
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
